
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: generic-seed
  title: Create Red Hat Enterprise Linux Ansible contentto manage time services and OS services.
  namespace: default
  tags:
    - aap-operations
    - pattern
    - rhel-pattern
spec:
  owner: RedHat
  type: wizard
  parameters:
    - title: Project data
      description: Please provide the details for creating the RHEL use cases in Ansible Automation Platform
      required:
        - token
        - organization
        - scmUrl
      properties:
        token:
          title: Token
          type: string
          description: Oauth2 token
          ui:field: AAPTokenField
          ui:backstage:
            review:
              show: false
          ui:widget: hidden
        organization:
          title: Organization
          description: Please choose the Inventory to use for the RHEL content
          resource: organizations
          type: string
          ui:field: AAPResourcePicker
          default:
            id: 1
            name: Default
        jobInventory:
          title: Inventory
          description: Please choose the Inventory to use for the RHEL content
          resource: inventories
          type: string
          ui:field: AAPResourcePicker
          default:
            id: 1
            name: Default
        scmUrl:
          title: Source control URL
          type: string
          ui:help: 'Source control URL: gitSourceControlUrlHelp'
          ui:options:
            rows: 5
          default: https://github.com/ansible/ansible-pattern-loader
          ui:widget: hidden
        scmBranch:
          title: Source control branch/tag/commit
          type: string
          ui:options:
            rows: 5
          default: main
          ui:help: 'Branch to checkout. In addition to branches, you can input tags, commit hashes, and arbitrary refs. Some commit hashes and refs may not be available unless you also provide a custom refspec.'
          ui:widget: hidden
    - title: Template data
      description: Provide template data
      required:
        - token
        # - useCases
        - playbook
        # - aapHostName
      properties:
        token:
          title: Token
          type: string
          description: Oauth2 token
          ui:field: AAPTokenField
          ui:backstage:
            review:
              show: false
        useCases:
          title: Use cases
          type: array
          minItems: 1
          items:
            type: object
            enum:
              - name: rhel
                url: https://github.com/ansible-collections/community.rhel_ops
                version: main
              - name: network
                url: https://github.com/redhat-cop/network.backup
                version: main
              - name: windows
                url: https://github.com/redhat-cop/infra.windows_ops
                version: main
              - name: cloud
                url: https://github.com/redhat-cop/cloud.aws_ops
                version: main
            enumNames:
              - RHEL
              # - Network
              # - Windows
              # - Cloud
          uniqueItems: true
          default: rhel
          # ui:widget: checkboxes
          ui:widget: hidden
        playbook:
          title: Playbook
          description: Select playbook
          type: string
          ui:options:
            rows: 5
          default: seed_portal_content.yml
          ui:widget: hidden
        aapHostName:
          title: AAP URL
          type: string
          ui:options:
            rows: 5
          default: https://34.205.78.142/
          ui:widget: hidden
        aapValidateCerts:
          title: AAP validate certs
          type: boolean
          default: false
          ui:widget: hidden
      errorMessage:
        properties:
          useCases: 'Select at least one use case.'
  steps:
     - id: create-project
       name: Create project
       action: rhaap:create-project
       input:
         token: ${{ parameters.token }}
         deleteIfExist: true
         values:
            projectName: 'RH AAP Demo Seed Job Template Project'
            projectDescription: 'RH AAP Demo Seed Job Template Project'
            organization: ${{ parameters.organization }}
            scmUrl: ${{ parameters.scmUrl }}
            scmBranch: ${{ parameters.scmBranch }}
            scmUpdateOnLaunch: true
     - id: create-ee
       name: Create execution environment
       action: rhaap:create-execution-environment
       input:
         token: ${{ parameters.token }}
         deleteIfExist: true
         values:
           environmentName: 'RH AAP Demo Seed Job Template execution environment'
           organization: ${{ parameters.organization }}
           image: 'quay.io/portal_mvp_patterns/ansible-pattern-loader:latest'
           pull: always
     - id: create-template
       name: Create job template
       action: rhaap:create-job-template
       input:
         token: ${{ parameters.token }}
         deleteIfExist: true
         values:
           templateName: 'RH AAP Demo Seed Job Template'
           templateDescription: 'RH AAP Demo Seed Job Template'
           project: ${{steps['create-project'].output.project }}
           organization: ${{ parameters.organization }}
           jobInventory: ${{ parameters.jobInventory }}
           playbook: ${{ parameters.playbook }}
           executionEnvironment: ${{steps['create-ee'].output.executionEnvironment }}
           extraVariables:
             aap_hostname: ${{ parameters.aapHostName }}
             aap_token: ${{ parameters.token }}
             aap_validate_certs: ${{ parameters.aapValidateCerts }}
             usecases: ${{ parameters.useCases }}
             seed_usecase: ${{ parameters.useCases | useCaseNameFilter }}
             organization_name: ${{ parameters.organization | resourceFilter('name')}}
     - id: launch-job
       name: Launch job template
       action: rhaap:launch-job-template
       input:
         token: ${{ parameters.token }}
         values:
           template: ${{steps['create-template'].output.template}}
     - id: clean-up
       name: Clean up
       action: rhaap:clean-up
       input:
         token: ${{ parameters.token }}
         values:
           project: ${{steps['create-project'].output.project }}
           executionEnvironment: ${{steps['create-ee'].output.executionEnvironment }}
           template: ${{steps['create-template'].output.template }}
     - id: create-showcase
       name: Create showcases
       action: rhaap:create-show-cases
       input:
         token: ${{ parameters.token }}
         values:
           organization: ${{ parameters.organization }}
           useCases: ${{ parameters.useCases }}
  output:
    text:
      - title: 'Job generic seed template executed successfully'
        content: |
          **Job ID:** `${{ steps['launch-job'].output.data.id }}`
    links:
      - title: View in RH AAP
        url: ${{ steps['launch-job'].output.data.url }}